### ISSUE TITLE
Struktur values, values-lhm

### ISSUE THREAD

**Issue by gislab-augsburg** [gislab-augsburg/helm-charts#22]
Ich hab die [values.yaml](https://github.com/gislab-augsburg/helm-charts/blob/main/charts/dave/values.yaml) und die [values-lhm.yaml](https://github.com/gislab-augsburg/helm-charts/blob/main/charts/dave/values-lhm.yaml) neu strukturiert, alles LHM-spezifische zu values-lhm, alles allgemeine zu values. 

@klml @DanielOber  

- Passt das so grundsätzlich aus eurer Sicht? 

- Muss von den Spring/ Keycloak Values (z.B. [hier](https://github.com/gislab-augsburg/helm-charts/blob/409186bc9da3651ed7333667f90745ee3b9be2f6/charts/dave/values.yaml#L40), [hier](https://github.com/gislab-augsburg/helm-charts/blob/409186bc9da3651ed7333667f90745ee3b9be2f6/charts/dave/values.yaml#L114), usw.) noch was rüber zu values-lhm? Sind die LHM-spezifisch, z.B. die ganzen Pfade, z.B.: https://github.com/gislab-augsburg/helm-charts/blob/409186bc9da3651ed7333667f90745ee3b9be2f6/charts/dave/values.yaml#L57C69-L57C139

- Soll noch soviel wie möglich in die [globalen EnvVars](https://github.com/gislab-augsburg/helm-charts/blob/d2f306be1a591c0cd6e1cb5175ba5f5e9b296729/charts/dave/values.yaml#L16), z.B. die ganzen Spring Werte, oder macht es Sinn, dass einzeln konfigurieren zu können?

**Comment by klml** [comment]
die [values-lhm.yaml](https://github.com/gislab-augsburg/helm-charts/blob/main/charts/dave/values-lhm.yaml) muss langfristig raus ins Projekt helm.

generell brauchen wir dann aber eine values-mininmal.yaml #23+
